# Site settings
title: Kubernetes by Google

description: Manage a cluster of Linux containers as a single system to accelerate Dev and simplify Ops with Kubernetes by Google.

baseurl: "" # the subpath of your site, e.g. /blog/

og: # if title, site_name or description are left blank, we will use the global
    # title and description. 
    title: 
    site_name:
    description:
    type: website
    image: /img/global/og_img.jpg

url: "http://kubernetes.io" # the base hostname & protocol for your site

google_analytics: "UA-36037335-10"

# Build settings
markdown: kramdown
#kramdown:
#    input: GFM
#    hard_wrap: false
#highlighter: pygments
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data", "lax_spacing", "space_after_headers", "disable_indented_code_blocks" ]
gems:
  - jekyll-redirect-from
sass:
    style: :compressed

logo:
    desktop: /img/desktop/nav_logo.svg
    mobile: /img/mobile/nav_logo.svg

nav:
 - label: Home
   url: /
   slug: home
   external: false
 - label: Getting Started
   url: /gettingstarted
   slug: gettingstarted
   external: false
 - label: Documentation
   url: /v1.1
   slug: v1.1
   external: false
 - label: Community
   url: /community
   slug: community
   external: false
 - label: Events
   url: /events
   slug: events
   external: false
 - label: Media
   url: /media
   slug: media
   external: false
 - label: Blog
   url: http://kubernetesio.blogspot.com/
   slug: blog
   external: true

footer:
    connect: Connect With Us!
    social: 
      - label: stackoverflow
        url: http://stackoverflow.com/questions/tagged/kubernetes
      - label: twitter
        url: https://twitter.com/kubernetesio
      - label: googleplus
        url: https://plus.google.com/u/0/b/116512812300813784482/116512812300813784482
            
    links:
      - label: Slack
        url: http://slack.k8s.io/
      - label: Mailing List
        url: "https://groups.google.com/forum/#!forum/google-containers" 

include: [v1.1, v1.0]

# Collections (for versioning docs)
collections:
   v1.1:
      output: true
   v1.0:
      output: true
# We have to make docs a collection, otherwise the `redirect_to` tag in _docs/index.md does not work.
   docs:
      output: true

# Page default settings
defaults:
-scope:
      path: v1.1
      type: page
values:
    layout: docwithnav
-scope:
      path: v1.0
      type: page
values:
    layout: docwithnav

theme: jekyll-theme-slate